version: '2'
services:
    daspanel-minio-fileserver:
        image: daspanel/minio-fileserver
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        ports:
            - "9000:9000"
        env_file:
            - daspanel.env
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


